// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/FedeBev/dkronc-go/client/default_operations"
	"github.com/FedeBev/dkronc-go/client/executions"
	"github.com/FedeBev/dkronc-go/client/jobs"
	"github.com/FedeBev/dkronc-go/client/members"
)

// Default dkron r e s t API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost:8080"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/v1"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new dkron r e s t API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *DkronRESTAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new dkron r e s t API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *DkronRESTAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new dkron r e s t API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *DkronRESTAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(DkronRESTAPI)
	cli.Transport = transport
	cli.DefaultOperations = default_operations.New(transport, formats)
	cli.Executions = executions.New(transport, formats)
	cli.Jobs = jobs.New(transport, formats)
	cli.Members = members.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// DkronRESTAPI is a client for dkron r e s t API
type DkronRESTAPI struct {
	DefaultOperations default_operations.ClientService

	Executions executions.ClientService

	Jobs jobs.ClientService

	Members members.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *DkronRESTAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.DefaultOperations.SetTransport(transport)
	c.Executions.SetTransport(transport)
	c.Jobs.SetTransport(transport)
	c.Members.SetTransport(transport)
}
