// Code generated by go-swagger; DO NOT EDIT.

package default_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewBusyParams creates a new BusyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBusyParams() *BusyParams {
	return &BusyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewBusyParamsWithTimeout creates a new BusyParams object
// with the ability to set a timeout on a request.
func NewBusyParamsWithTimeout(timeout time.Duration) *BusyParams {
	return &BusyParams{
		timeout: timeout,
	}
}

// NewBusyParamsWithContext creates a new BusyParams object
// with the ability to set a context for a request.
func NewBusyParamsWithContext(ctx context.Context) *BusyParams {
	return &BusyParams{
		Context: ctx,
	}
}

// NewBusyParamsWithHTTPClient creates a new BusyParams object
// with the ability to set a custom HTTPClient for a request.
func NewBusyParamsWithHTTPClient(client *http.Client) *BusyParams {
	return &BusyParams{
		HTTPClient: client,
	}
}

/* BusyParams contains all the parameters to send to the API endpoint
   for the busy operation.

   Typically these are written to a http.Request.
*/
type BusyParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the busy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BusyParams) WithDefaults() *BusyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the busy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BusyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the busy params
func (o *BusyParams) WithTimeout(timeout time.Duration) *BusyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the busy params
func (o *BusyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the busy params
func (o *BusyParams) WithContext(ctx context.Context) *BusyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the busy params
func (o *BusyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the busy params
func (o *BusyParams) WithHTTPClient(client *http.Client) *BusyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the busy params
func (o *BusyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *BusyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
