// Code generated by go-swagger; DO NOT EDIT.

package default_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FedeBev/dkronc-go/v3/models"
)

// GetLeaderReader is a Reader for the GetLeader structure.
type GetLeaderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLeaderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLeaderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetLeaderOK creates a GetLeaderOK with default headers values
func NewGetLeaderOK() *GetLeaderOK {
	return &GetLeaderOK{}
}

/* GetLeaderOK describes a response with status code 200, with default header values.

Successful response
*/
type GetLeaderOK struct {
	Payload *models.Member
}

func (o *GetLeaderOK) Error() string {
	return fmt.Sprintf("[GET /leader][%d] getLeaderOK  %+v", 200, o.Payload)
}
func (o *GetLeaderOK) GetPayload() *models.Member {
	return o.Payload
}

func (o *GetLeaderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Member)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
