// Code generated by go-swagger; DO NOT EDIT.

package default_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FedeBev/dkronc-go/models"
)

// LeaveReader is a Reader for the Leave structure.
type LeaveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LeaveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLeaveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLeaveOK creates a LeaveOK with default headers values
func NewLeaveOK() *LeaveOK {
	return &LeaveOK{}
}

/* LeaveOK describes a response with status code 200, with default header values.

Successful response
*/
type LeaveOK struct {
	Payload []*models.Member
}

func (o *LeaveOK) Error() string {
	return fmt.Sprintf("[POST /leave][%d] leaveOK  %+v", 200, o.Payload)
}
func (o *LeaveOK) GetPayload() []*models.Member {
	return o.Payload
}

func (o *LeaveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
