// Code generated by go-swagger; DO NOT EDIT.

package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FedeBev/dkronc-go/pkg/models"
)

// RunJobReader is a Reader for the RunJob structure.
type RunJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RunJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewRunJobAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRunJobAccepted creates a RunJobAccepted with default headers values
func NewRunJobAccepted() *RunJobAccepted {
	return &RunJobAccepted{}
}

/* RunJobAccepted describes a response with status code 202, with default header values.

Successful response
*/
type RunJobAccepted struct {
	Payload *models.Job
}

func (o *RunJobAccepted) Error() string {
	return fmt.Sprintf("[POST /jobs/{job_name}][%d] runJobAccepted  %+v", 202, o.Payload)
}
func (o *RunJobAccepted) GetPayload() *models.Job {
	return o.Payload
}

func (o *RunJobAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Job)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
