// Code generated by go-swagger; DO NOT EDIT.

package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FedeBev/dkronc-go/pkg/models"
)

// ShowJobByNameReader is a Reader for the ShowJobByName structure.
type ShowJobByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ShowJobByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewShowJobByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewShowJobByNameOK creates a ShowJobByNameOK with default headers values
func NewShowJobByNameOK() *ShowJobByNameOK {
	return &ShowJobByNameOK{}
}

/* ShowJobByNameOK describes a response with status code 200, with default header values.

Successful response
*/
type ShowJobByNameOK struct {
	Payload *models.Job
}

func (o *ShowJobByNameOK) Error() string {
	return fmt.Sprintf("[GET /jobs/{job_name}][%d] showJobByNameOK  %+v", 200, o.Payload)
}
func (o *ShowJobByNameOK) GetPayload() *models.Job {
	return o.Payload
}

func (o *ShowJobByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Job)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
