// Code generated by go-swagger; DO NOT EDIT.

package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewToggleJobParams creates a new ToggleJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewToggleJobParams() *ToggleJobParams {
	return &ToggleJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewToggleJobParamsWithTimeout creates a new ToggleJobParams object
// with the ability to set a timeout on a request.
func NewToggleJobParamsWithTimeout(timeout time.Duration) *ToggleJobParams {
	return &ToggleJobParams{
		timeout: timeout,
	}
}

// NewToggleJobParamsWithContext creates a new ToggleJobParams object
// with the ability to set a context for a request.
func NewToggleJobParamsWithContext(ctx context.Context) *ToggleJobParams {
	return &ToggleJobParams{
		Context: ctx,
	}
}

// NewToggleJobParamsWithHTTPClient creates a new ToggleJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewToggleJobParamsWithHTTPClient(client *http.Client) *ToggleJobParams {
	return &ToggleJobParams{
		HTTPClient: client,
	}
}

/* ToggleJobParams contains all the parameters to send to the API endpoint
   for the toggle job operation.

   Typically these are written to a http.Request.
*/
type ToggleJobParams struct {

	/* JobName.

	   The job that needs to be toggled.
	*/
	JobName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the toggle job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ToggleJobParams) WithDefaults() *ToggleJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the toggle job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ToggleJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the toggle job params
func (o *ToggleJobParams) WithTimeout(timeout time.Duration) *ToggleJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the toggle job params
func (o *ToggleJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the toggle job params
func (o *ToggleJobParams) WithContext(ctx context.Context) *ToggleJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the toggle job params
func (o *ToggleJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the toggle job params
func (o *ToggleJobParams) WithHTTPClient(client *http.Client) *ToggleJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the toggle job params
func (o *ToggleJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJobName adds the jobName to the toggle job params
func (o *ToggleJobParams) WithJobName(jobName string) *ToggleJobParams {
	o.SetJobName(jobName)
	return o
}

// SetJobName adds the jobName to the toggle job params
func (o *ToggleJobParams) SetJobName(jobName string) {
	o.JobName = jobName
}

// WriteToRequest writes these params to a swagger request
func (o *ToggleJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param job_name
	if err := r.SetPathParam("job_name", o.JobName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
