// Code generated by go-swagger; DO NOT EDIT.

package default_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetIsLeaderParams creates a new GetIsLeaderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetIsLeaderParams() *GetIsLeaderParams {
	return &GetIsLeaderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetIsLeaderParamsWithTimeout creates a new GetIsLeaderParams object
// with the ability to set a timeout on a request.
func NewGetIsLeaderParamsWithTimeout(timeout time.Duration) *GetIsLeaderParams {
	return &GetIsLeaderParams{
		timeout: timeout,
	}
}

// NewGetIsLeaderParamsWithContext creates a new GetIsLeaderParams object
// with the ability to set a context for a request.
func NewGetIsLeaderParamsWithContext(ctx context.Context) *GetIsLeaderParams {
	return &GetIsLeaderParams{
		Context: ctx,
	}
}

// NewGetIsLeaderParamsWithHTTPClient creates a new GetIsLeaderParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetIsLeaderParamsWithHTTPClient(client *http.Client) *GetIsLeaderParams {
	return &GetIsLeaderParams{
		HTTPClient: client,
	}
}

/* GetIsLeaderParams contains all the parameters to send to the API endpoint
   for the get is leader operation.

   Typically these are written to a http.Request.
*/
type GetIsLeaderParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get is leader params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIsLeaderParams) WithDefaults() *GetIsLeaderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get is leader params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIsLeaderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get is leader params
func (o *GetIsLeaderParams) WithTimeout(timeout time.Duration) *GetIsLeaderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get is leader params
func (o *GetIsLeaderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get is leader params
func (o *GetIsLeaderParams) WithContext(ctx context.Context) *GetIsLeaderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get is leader params
func (o *GetIsLeaderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get is leader params
func (o *GetIsLeaderParams) WithHTTPClient(client *http.Client) *GetIsLeaderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get is leader params
func (o *GetIsLeaderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetIsLeaderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
