// Code generated by go-swagger; DO NOT EDIT.

package default_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewLeaveParams creates a new LeaveParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLeaveParams() *LeaveParams {
	return &LeaveParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLeaveParamsWithTimeout creates a new LeaveParams object
// with the ability to set a timeout on a request.
func NewLeaveParamsWithTimeout(timeout time.Duration) *LeaveParams {
	return &LeaveParams{
		timeout: timeout,
	}
}

// NewLeaveParamsWithContext creates a new LeaveParams object
// with the ability to set a context for a request.
func NewLeaveParamsWithContext(ctx context.Context) *LeaveParams {
	return &LeaveParams{
		Context: ctx,
	}
}

// NewLeaveParamsWithHTTPClient creates a new LeaveParams object
// with the ability to set a custom HTTPClient for a request.
func NewLeaveParamsWithHTTPClient(client *http.Client) *LeaveParams {
	return &LeaveParams{
		HTTPClient: client,
	}
}

/* LeaveParams contains all the parameters to send to the API endpoint
   for the leave operation.

   Typically these are written to a http.Request.
*/
type LeaveParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the leave params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LeaveParams) WithDefaults() *LeaveParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the leave params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LeaveParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the leave params
func (o *LeaveParams) WithTimeout(timeout time.Duration) *LeaveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the leave params
func (o *LeaveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the leave params
func (o *LeaveParams) WithContext(ctx context.Context) *LeaveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the leave params
func (o *LeaveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the leave params
func (o *LeaveParams) WithHTTPClient(client *http.Client) *LeaveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the leave params
func (o *LeaveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *LeaveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
