// Code generated by go-swagger; DO NOT EDIT.

package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewShowJobByNameParams creates a new ShowJobByNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewShowJobByNameParams() *ShowJobByNameParams {
	return &ShowJobByNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewShowJobByNameParamsWithTimeout creates a new ShowJobByNameParams object
// with the ability to set a timeout on a request.
func NewShowJobByNameParamsWithTimeout(timeout time.Duration) *ShowJobByNameParams {
	return &ShowJobByNameParams{
		timeout: timeout,
	}
}

// NewShowJobByNameParamsWithContext creates a new ShowJobByNameParams object
// with the ability to set a context for a request.
func NewShowJobByNameParamsWithContext(ctx context.Context) *ShowJobByNameParams {
	return &ShowJobByNameParams{
		Context: ctx,
	}
}

// NewShowJobByNameParamsWithHTTPClient creates a new ShowJobByNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewShowJobByNameParamsWithHTTPClient(client *http.Client) *ShowJobByNameParams {
	return &ShowJobByNameParams{
		HTTPClient: client,
	}
}

/* ShowJobByNameParams contains all the parameters to send to the API endpoint
   for the show job by name operation.

   Typically these are written to a http.Request.
*/
type ShowJobByNameParams struct {

	/* JobName.

	   The job that needs to be fetched.
	*/
	JobName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the show job by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ShowJobByNameParams) WithDefaults() *ShowJobByNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the show job by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ShowJobByNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the show job by name params
func (o *ShowJobByNameParams) WithTimeout(timeout time.Duration) *ShowJobByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the show job by name params
func (o *ShowJobByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the show job by name params
func (o *ShowJobByNameParams) WithContext(ctx context.Context) *ShowJobByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the show job by name params
func (o *ShowJobByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the show job by name params
func (o *ShowJobByNameParams) WithHTTPClient(client *http.Client) *ShowJobByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the show job by name params
func (o *ShowJobByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJobName adds the jobName to the show job by name params
func (o *ShowJobByNameParams) WithJobName(jobName string) *ShowJobByNameParams {
	o.SetJobName(jobName)
	return o
}

// SetJobName adds the jobName to the show job by name params
func (o *ShowJobByNameParams) SetJobName(jobName string) {
	o.JobName = jobName
}

// WriteToRequest writes these params to a swagger request
func (o *ShowJobByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param job_name
	if err := r.SetPathParam("job_name", o.JobName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
