// Code generated by go-swagger; DO NOT EDIT.

package executions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FedeBev/dkronc-go/models"
)

// ListExecutionsByJobReader is a Reader for the ListExecutionsByJob structure.
type ListExecutionsByJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListExecutionsByJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListExecutionsByJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListExecutionsByJobOK creates a ListExecutionsByJobOK with default headers values
func NewListExecutionsByJobOK() *ListExecutionsByJobOK {
	return &ListExecutionsByJobOK{}
}

/* ListExecutionsByJobOK describes a response with status code 200, with default header values.

Successful response
*/
type ListExecutionsByJobOK struct {
	Payload []*models.Execution
}

func (o *ListExecutionsByJobOK) Error() string {
	return fmt.Sprintf("[GET /jobs/{job_name}/executions][%d] listExecutionsByJobOK  %+v", 200, o.Payload)
}
func (o *ListExecutionsByJobOK) GetPayload() []*models.Execution {
	return o.Payload
}

func (o *ListExecutionsByJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
