// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Processors Processor plugins used to process executions results of this job
// Example: {"files":{"forward":true}}
//
// swagger:model processors
type Processors map[string]map[string]string

// Validate validates this processors
func (m Processors) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this processors based on context it is used
func (m Processors) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
