// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Restore Each job restore result.
// Example: success create job_1
//
// swagger:model restore
type Restore string

// Validate validates this restore
func (m Restore) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this restore based on context it is used
func (m Restore) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
